# Bounding box
x_min: -25
x_max: 7
y_min: -28
y_max: 60
z_min: -1
z_max: 5

base_height: 0.6
base_radius: 0.5
ground_robot: true
connection_radius: 4.0
too_close_radius: 1.0

# Start positions
start:
  x: 1.0
  y: 0.0
  z: 1.0 # robot 

#1.83343 2.9898 -0.0913357
#3.41294 2.82653 0.32438
path_start:
  x: 1.83343
  y: 1.9898
  z: 1

path_target:
  x: 1.8
  y: 2.4
  z: 1

# Thresholds
frontier_creation_threshold: 0.3
frontier_jump_threshold: 3.0
frontier_split_threshold: 2.0
min_flowback_creation_threshold: 1
min_flowback_creation_radius_threshold: 0.25
bad_loop: true

# Ray and node settings
min_node_radius: 0.8
search_margin: 0.1
max_ray_length: 2.5
max_expansion_ray_length: 2.5
max_height_diff: 1.5
sampling_density: 80
max_facets_grouped: 10
resolution: 0.1

